name: Sync fork with upstream
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    strategy:
      # Using matrix to trigger sync in multiple branches.
      matrix:
        branch:
          - master
          - staging
    permissions:
      contents: write
    steps:
      - uses: thiagokokada/merge-upstream@v1.0.2
        id: merge-upstream
        with:
          branch: ${{ matrix.branch }}
          token: ${{ secrets.PAT_TOKEN }}
      - run: |
          # The job has the following outputs that matches the API response.
          # They may be useful for further automation.
          echo "${{ steps.merge-upstream.outputs.message }}"
          echo "${{ steps.merge-upstream.outputs.merge-type }}"
          echo "${{ steps.merge-upstream.outputs.base-branch }}"
